server:
  port: 8080

spring:
  main:
    banner-mode: "off"
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:file:~/test5
  jpa:
    database: h2
    ddl-auto: create-drop

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: com.richard.kafkaproject.serializer.UpdateCustomerDTODeserializer
      value-deserializer: com.richard.kafkaproject.serializer.UpdateCustomerDTODeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: com.richard.kafkaproject.serializer.UpdateCustomerDTOSerializer
      value-serializer: com.richard.kafkaproject.serializer.UpdateCustomerDTOSerializer
debug: false


